# Generated by Django 4.1.7 on 2023-04-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=288)),
                ('amount', models.CharField(max_length=288)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288)),
                ('key_words', models.CharField(max_length=288)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=288)),
                ('amount', models.CharField(max_length=288)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statement.tag')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
