# Generated by Django 4.1.7 on 2023-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='tags',
        ),
        migrations.AddField(
            model_name='expenses',
            name='tags',
            field=models.ManyToManyField(to='statement.tag'),
        ),
    ]
