# Generated by Django 4.1.7 on 2023-02-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_income_alter_expenses_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['date']},
        ),
    ]
